apiVersion: apps/v1
kind:  Deployment
metadata:
  name:  n8n-deployment
  namespace: default
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers: 
        - name: n8n
          image: 058264399739.dkr.ecr.us-east-1.amazonaws.com/agent_repo:n8n
          ports:
            - containerPort: 5678
          env:
            # Basic Auth (hardcoded - change these values)
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              value: "admin"
            - name: N8N_BASIC_AUTH_PASSWORD
              value: "Slimane2003"

            # Disable email login
            - name:  N8N_USER_MANAGEMENT_DISABLED
              value: "true"

            # Allow cookies over HTTP (dev only)
            - name: N8N_SECURE_COOKIE
              value: "false"

            # Host + protocol
            - name: N8N_HOST
              value: "n8n-service"
            - name: N8N_PROTOCOL
              value: "http"
            - name: N8N_PORT
              value: "5678"

            # Webhook URL (use service DNS)
            - name: N8N_WEBHOOK_URL
              value: "http://n8n-service"

            # Disable telemetry
            - name: N8N_DIAGNOSTICS_ENABLED
              value: "false"

          resources: 
            requests:
              cpu:  "250m"
              memory:  "512Mi"
            limits: 
              cpu: "500m"
              memory: "1Gi"